<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <OutputPath Condition="'$(Configuration)'=='Debug'">..\bin\debug\</OutputPath>
    <GenerateDocumentationFile Condition="'$(Configuration)'=='Release'">true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenSourceToolkit.Core\OpenSourceToolkit.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FIGLet" Version="1.1.0" />
    <PackageReference Include="SkiaSharp" Version="3.119.2" />
  </ItemGroup>

</Project>
